# Generated by Django 4.2.5 on 2023-12-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_factura_modo_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='referencia',
            new_name='nombre',
        ),
    ]
