# Generated by Django 4.2.5 on 2023-12-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_factura_modo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='linea',
            field=models.CharField(choices=[('Corolla', 'Corolla'), ('Camry', 'Camry'), ('Prius', 'Prius'), ('Rav4', 'Rav4'), ('Highlander', 'Highlander'), ('Tacoma', 'Tacoma'), ('Sienna', 'Sienna'), ('C-HR', 'C-HR'), ('Avalon', 'Avalon'), ('4Runner', '4Runner'), ('Mazda3', 'Mazda 3'), ('Mazda6', 'Mazda 6'), ('CX-5', 'CX-5'), ('MX-5 Miata', 'MX-5 Miata'), ('CX-9', 'CX-9'), ('Mazda2', 'Mazda 2'), ('Mazda5', 'Mazda 5'), ('RX-8', 'RX-8'), ('CX-30', 'CX-30'), ('MX-30', 'MX-30'), ('Civic', 'Civic'), ('Accord', 'Accord'), ('CR-V', 'CR-V'), ('Pilot', 'Pilot'), ('Fit', 'Fit'), ('HR-V', 'HR-V'), ('Ridgeline', 'Ridgeline'), ('Odyssey', 'Odyssey'), ('Insight', 'Insight'), ('Passport', 'Passport'), ('Focus', 'Focus'), ('Fusion', 'Fusion'), ('Escape', 'Escape'), ('Explorer', 'Explorer'), ('Mustang', 'Mustang'), ('Edge', 'Edge'), ('F-150', 'F-150'), ('Expedition', 'Expedition'), ('Ranger', 'Ranger'), ('EcoSport', 'EcoSport'), ('Malibu', 'Malibu'), ('Cruze', 'Cruze'), ('Equinox', 'Equinox'), ('Traverse', 'Traverse'), ('Silverado', 'Silverado'), ('Blazer', 'Blazer'), ('Suburban', 'Suburban'), ('Colorado', 'Colorado'), ('Tahoe', 'Tahoe'), ('Spark', 'Spark')], max_length=50, null=True, verbose_name='Linea'),
        ),
        migrations.AlterField(
            model_name='car',
            name='marca',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Mazda', 'Mazda'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet')], max_length=50, null=True, verbose_name='Marca'),
        ),
    ]
